import mini from '../styles/mini-default.min.css';
import style from  '../styles/style.scss';
import home from  '../styles/home.scss';
import input from  '../styles/input.scss';
import topbar from  '../styles/topbar.scss';
import footer from  '../styles/footer.scss';
import card from  '../styles/card.scss';
import dropdown from  '../styles/dropdown.scss';
import tooltip from  '../styles/tooltip.scss';
