import BebasNeue from  '../fonts/BebasNeue-Regular.ttf';
import OpenSans from  '../fonts/OpenSans-Regular.ttf';
import OpenSansLight from  '../fonts/OpenSans-Light.ttf';
import OpenSansBold from  '../fonts/OpenSans-Bold.ttf';
import OpenSansExtraBold from  '../fonts/OpenSans-ExtraBold.ttf';
import Symbol from  '../fonts/symbol-signs.otf';
import mini from '../styles/mini-default.min.css';
import style from  '../styles/style.scss';
import home from  '../styles/home.scss';
import input from  '../styles/input.scss';
import topbar from  '../styles/topbar.scss';
import footer from  '../styles/footer.scss';
import card from  '../styles/card.scss';
import dropdown from  '../styles/dropdown.scss';
import tooltip from  '../styles/tooltip.scss';
import $ from "jquery";
window.$ = require('jquery');
window.jQuery = require('jquery');
import  '../scripts/d3.v3.min.js';
